### ISSUE TITLE
Informazione su "Screen Constants"

### ISSUE THREAD

**Issue by zerolele12** [filipposerafini/LiveQuizBot#1]
Salve, voglio adattare questo codice per un samsung s4.. solo che so trovando delle complicazioni con le "screen constants". Sono riuscito ad adattare le costanti per il quesito solo che sto trovando difficolta' nel adattare le option, gentilmente mi potrebbe dare qualche suggerimento su come adattarle? Grazie per l'aiuto

**Comment by zerolele12** [comment]
Perchè sono riuscito ad adattare le option quando il quesito è a 3 righe, invece trovo problemi quando è a 2 o a 1 riga

**Comment by filipposerafini** [comment]
Ciao. In OPTION_POSITION vanno inserite le posizioni dei bordi superiori delle opzioni nel caso di un quesito con una sola riga. In caso di più righe poi tutto si dovrebbe adattare, a patto che in uno schermo con un form factor diverso tutti gli spazi siano identici a quelli che ho inserito io. Se non dovesse funzionare allora andrebbero riadattate anche ROW_HEIGHT e OPTION_HEIGHT.

**Comment by zerolele12** [comment]
Grazie mille, sono riuscito a sistemarlo
